// Regenerates src/modules/guide/okf-spec.ts from ../../vendor/okf/SPEC.md (the single source).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here = path.dirname(fileURLToPath(import.meta.url));
const spec = fs.readFileSync(path.join(here, "../../../vendor/okf/SPEC.md"), "utf8");
const version = (/\*\*Version ([0-9.]+)\*\*/.exec(spec) ?? [, "unknown"])[1];
const out = `/**
 * GENERATED by scripts/vendor-okf.mjs from vendor/okf/SPEC.md. Do not edit; edit the source and rerun.
 * The Open Knowledge Format specification (Apache-2.0, Copyright Google LLC); see vendor/okf/NOTICE.md.
 */
export const OKF_SPEC_VERSION = ${JSON.stringify(version)};
export const OKF_SPEC_SOURCE = "https://github.com/GoogleCloudPlatform/open-knowledge-format/blob/main/SPEC.md";
export const OKF_SPEC: string = ${JSON.stringify(spec)};
`;
fs.writeFileSync(path.join(here, "../src/modules/guide/okf-spec.ts"), out);
console.log(`okf-spec.ts regenerated (version ${version}, ${spec.split(/\s+/).length} words)`);
